### ISSUE TITLE
Fasteners for the bottom cover/plexiglass

### ISSUE THREAD

**Issue by rudenick1** [veikman/dactyl-keyboard#10]
Hey man, I continue learning Clojure with your project in the background. I also have my Ender 3 Pro 3d printer. It might take me a while to get to the level to make the changes I have in mind so I decided to address one of them (fasteners) beforehand. Maybe you will like the idea.

Some users have trouble making adjustments to print small circles on the printer bed. 
- Making the fastener outer wall shape square may help with the printing process.

Using solid plastic for the screw holes may result in cracks in the case, especially if the walls are thin.
- Making fastener walls bigger allows using 30% infill. So the screw can "dig in" to the plastic without risking unintended cracks. It should help with the stiffness in a way too.
- Alternatively, on top of the fastener object if it's nice and fat and square you can add a hexagonal hole for a hexagonal nut. For the durability and some additional weight.

Offtop:
- How do you feel about the case stiffness (when pressing it from the top) and weight?

**Comment by veikman** [comment]
I take it you are referring to the threaded anchors for screws that connect bottom plates to the case. The function that describes their outer shape is called `anchor-positive`. You would like to have the option of replacing the cylinders and sphere in there with a cuboid, and/or increasing their diameter with respect to the fasteners themselves, and/or adding nut bosses?

Among these ideas I prefer the option of making thickness configurable, so I have implemented that for a start. The anchors are also more sturdy by default in [this commit](https://github.com/veikman/dactyl-keyboard/commit/5eb55f99b0382c96e999e09343b25ad24f52b71c). Please let me know if that is inadequate; I’m closing the issue for now.

A square profile would be easy to design, but I’m not sure how it’s supposed to help; I have not seen the problem you describe with small circles. I am big fun of nut bosses in general but I don’t know of a good, easily configured and printed way to use them for this detail without introducing the risk of dislodging a nut inside the case as you try to close it.

⸻

As for your off-topic question, I’m satisfied with the stiffness of PLA- and Amphora-like materials with default.yaml settings and about 30-40% infill. I have not experimented with a thicker case or very high infill. I suppose a more massive case might improve the feel but I believe there is more to be gained by adding a heavy connecting rod, wrist rests etc. Perhaps one day somebody will laser-sinter an all-metal DMOTE and offer a comparison. :smile:
