### ISSUE TITLE
Number keys

### ISSUE THREAD

**Issue by kalium99** [veikman/dactyl-keyboard#12]
Hi Viktor,

Not so much an issue, but I'm building a DMOTE keyboard (from the default config) and I'm wondering how you handle numerical keys? I notice in your demo you seem to handle them fine, but I can't see any pictures of how that works. Obviously It's something that can be customised, but I'm curious to know what has worked well for you.

Cheers.

**Comment by veikman** [comment]
Hi Jerry,

The QMK keymap I use is up [here](https://github.com/qmk/qmk_firmware/blob/master/keyboards/handwired/dactyl_manuform/dmote/62key/keymaps/default/keymap.c). In it, the middle key of the right-hand thumb cluster activates a numeric layer where the digits are all on the home row: 1 is on the A key etc. This works well enough for me.

Good luck with your build!
