### ISSUE TITLE
cad/aux.clj has file name "aux", cause the repo fail to clone on Windows.

### ISSUE THREAD

**Issue by milizhang** [veikman/dactyl-keyboard#13]
Hi,

Just figured this out while trying to play a little bit with DMOTE on my most powerful workstation which runs Windows. One of the source file in this repository is called aux.cij, however as "AUX" is a preserved file name Windows inherited from the MS-DOS era, the result is that this file cannot be created when Git is trying to clone this repository on Windows.

While I think the author probably does not really use Windows, I would really appreciate if anyone can make the project more inclusive to Windows users by renaming the file (and probably the associated namespace) on another OS.

Thanks.

**Comment by veikman** [comment]
Indeed I don’t use Windows, and here’s one of the 1000 reasons. I was not aware of the restriction. Thank you for bringing it to my attention. I’ll rename the file.
