### ISSUE TITLE
Kailh Compatibility

### ISSUE THREAD

**Issue by RaoulDuke-Esq** [veikman/dactyl-keyboard#19]
I'm trying to adapt mx.yaml to support Kailh switches.  I've added key-mount-thickness: 1.4 which makes the switch slot thin enough for the switches' built-in clips to work.  However, I couldn't find how to shrink or get rid of the mx nubs in the side of the switch slots.  How does one adjust the nubs?

**Comment by veikman** [comment]
The nubs are not yet adjustable for Kailh from the configuration layer. I would like to support Kailh switches, but I will have to get some first, or find detailed specs, and then add them to the application as a configurable type. I am currently working on unrelated features.

**Comment by StephenHogsten** [comment]
Are (these specs](http://www.kailh.com/en/Products/Mechanical_keyboard_switch/165.html) detailed enough (at the bottom click dimensions)?  

I guess I don't know for sure if the bases for all the different types are identical but I would think would be.

**Comment by veikman** [comment]
For some reason, www.kailh.com has been variously unreachable and extremely slow for the past month. The specs there are pretty good. They don’t provide full details on the nubs, but together with photos elsewhere I now have a fair idea of what to do.

Kailh makes a bunch of different styles. I assume this issue pertains to the [PG1511 series](https://deskthority.net/wiki/Kailh_PG1511_series). Correct me if I’m wrong.

**Comment by boogerlad** [comment]
I'd be happy to buy these [optical](https://www.aliexpress.com/item/33027003832.html) switches for you, Viktor. I talked with a Kailh support representative, and the model number for the optical switches is CPG151101D206, which strangely is not visible on their site. I also received a screenshot of the datasheet, with dimensions very similar to the link posted by Stephen.
![kailh_optical](https://user-images.githubusercontent.com/1903750/76158751-8b600f00-60ef-11ea-9311-d610b6b88606.jpg)

**Comment by CreamyCookie** [comment]
No idea, if this could help, but there's a pull request by @rishka on tshort's repository about adding Kaihl support: https://github.com/tshort/dactyl-keyboard/pull/36 (if given permission to use said coded, of course)

**Comment by veikman** [comment]
Kailh compatibility has been added. Set `switch-type` → `kailh-pg1511`, as demonstrated in [this](https://github.com/veikman/dactyl-keyboard/blob/master/test/config/mount_types.yaml) new bundled configuration file. Support includes the PG1511 series, with two caveats:

* Some entries in the series have non-standard travel, but the difference is small enough that you almost certainly don’t need to work around it. If you do, set `clearance` → `use-key-style` to `false` (the default value), and `clearance` → `nominal` to whatever you need.
* More importantly, some PG1511 switches block out part of the base of the stem. This includes BOX-type Kailh switches as well as @boogerlad’s CPG151101D206. The DMOTE application can now make keyboard *cases* that fit these, *but* the `dmote-keycap` library cannot yet make working custom *keycaps*. As long as you’re using keycaps from other sources, that won’t be a problem.

**Comment by CreamyCookie** [comment]
@veikman Thanks! DMOTE is an amazing project. (I'm especially fond of the thumb cluster you've created.)
