### ISSUE TITLE
How get started

### ISSUE THREAD

**Issue by guategeek** [veikman/dactyl-keyboard#27]
Hi, first off sorry if this is the wrong place to ask this.

I have been following this repo for a while, as it looks like the closest thing to my dream keyboard as possible (though I think a little screen showing what layer or profile your on would be cool). I have never built a keyboard before, so I'm unsure what I would need to buy to get started on this. I live in Guatemala so not much is available here, but in about two weeks I have a way to get stuff from the U.S.A. I do have an Ender 3, so I should be able to print the case. I just don't want to pick up the wrong stuff, as I won't be able to return it and replacing it would be challenging.

I was wondering if I could get some help in what I need bare minimum to get this project started.

----

**Switches:**
I know I need switches and I'm curious if any "MX style" switch will work, like for example [Drop Halo Cherry-Style](https://www.amazon.com/dp/B083TRL6HB) or would I need actual Cherry MX's like [MX Browns](https://www.amazon.com/dp/B08BXK68KF).

If I get the clear ones, that means I could have a few LEDs inside the keyboard and it would shine through so I can see the edges of the keycaps right?

**Diodes:**
Is this what I need between the columns or rows when wiring? [1N4148](https://www.amazon.com/dp/B079KJ91JZ)

**Keycaps:**
Do I need any special type of keycap? Or could I say buy a cheap kit like this [Replacement Keycaps](https://www.amazon.com/dp/B019OAQ6VI) and use all the small ones from it? Also I'm assuming a double shot keycap means that with some LEDs in the keyboard you could see the legends lite up?

**Micro-controller:**
From my understanding I need two, on for each half of the keyboard. Are there any you would suggest for a first time build? Like a Teensy++ 2.0 or is something smaller like a Teensy 2.0 better, or go for the 3.2? I would like to add some LED's for back-lighting as mentioned above so I don't know if that affects this choice.

**LEDs:**
What would I need for LED's for say the indicator, and the back-lighting, is it possible to use RGB ones where say the back-lighing changes per profile/layer?

----

Sorry to bomb you guys with so many questions. Thanks for this awesome project and any help you can give.

**Comment by jotomo** [comment]
There's a build guide that should answer a bunch of your questions: https://viktor.eikman.se/article/concertina-v060-build-guide/
Note that the current design is ALPS-switches only (the DMOTE has a config for MX-switches, but the Concertina does not at this time). HTH

**Comment by veikman** [comment]
Hi! jotomo’s answer is very good. I’ll fill in a couple of details.

> I know I need switches and I'm curious if any "MX style" switch will work

The DMOTE application supports configuring a keyboard for classic MX-style switches, but there’s an important difference between the base of the switch (how it fits into the keyboard case) and the stem (how it fits into the keycap). The specific switch you linked to is made by Kaihua and may have a different sort of base. In that case, it may be possible to retrofit a print for it by removing or reshaping material with a file and soldering iron, and of course, it is also possible to expand the application itself for more switches.

> If I get the clear ones, that means I could have a few LEDs inside the keyboard and it would shine through so I can see the edges of the keycaps right?

Right.

> Is this what I need between the columns or rows when wiring? [1N4148]

That’s right.

> Do I need any special type of keycap?

For the Concertina, yes, you need to print your own keycaps. For the bundled version of the DMOTE, you currently need to print some caps and either print or buy others; it’s an unfortunate situation described [here](https://github.com/veikman/dactyl-keyboard/issues/21). That issue links to a fork that lets you use normal store-bought keycaps for all keys on a DMOTE.

> Also I'm assuming a double shot keycap means that with some LEDs in the keyboard you could see the legends lite up?

Be careful with that. Most double-shot keycaps use two types of opaque plastic and will therefore not be translucent.

> From my understanding I need two, on for each half of the keyboard.

That is correct for the DMOTE. You only need one for a Concertina, which is not split. I use Pro Micros with both designs. That leaves room for backlighting.

> What would I need for LED's for say the indicator, and the back-lighting, is it possible to use RGB ones where say the back-lighing changes per profile/layer?

That is certainly possible. Most people use WS2812 LEDs, which are individually addressable. If you are comfortable programming in C, you can make them do anything you want.

**Comment by veikman** [comment]
Closing this, partly for lack of activity, partly because there has been some improvement: The basic DMOTE design no longer uses a mix of custom and ordinary keycaps; `intro.md` now links to several build guides; and there is a new, more extensive [Concertina v0.7.0 build guide](https://viktor.eikman.se/article/concertina-v070-build-guide/).
