### ISSUE TITLE
How to remove rear housing?

### ISSUE THREAD

**Issue by Zentrik** [veikman/dactyl-keyboard#28]
I wish to make the north of the DMOTE more like the dactyl manuform, i.e. being a lot smaller and having a connector hole in the bottom north west. To make the north end smaller, I disabled the rear-housing and the reflection-port by setting `include: false` for both however, I can not work out how to then add a wall on the north side.
Thanks

**Comment by veikman** [comment]
Hi Zentrik,

I’ve gotten this question before, so I thought it best to add a file for it.

![20201111_20h26m23s_grim](https://user-images.githubusercontent.com/9773711/98855509-6846e580-245c-11eb-8bbd-ae251eb55e6d.png)

Check it out, caveats and all:
https://github.com/veikman/dactyl-keyboard/blob/master/config/dmote/no_rear_housing.yaml

**Comment by Zentrik** [comment]
Thank you
