### ISSUE TITLE
How to generate the wrist rests?

### ISSUE THREAD

**Issue by Zentrik** [veikman/dactyl-keyboard#29]
What are the advantages to using `threaded_caseside.yaml` over `threaded_mutual.yaml`. Also, is there a reason the wrist rest is by default at an angle to the keyboard, is it more ergonomic?

**Comment by veikman** [comment]
The principal difference lies in the type of authority, which you can read about [here](https://github.com/veikman/dactyl-keyboard/blob/master/doc/options-wrist-rest-mounts.md#user-content-authority).

In the DMOTE _application_, the wrist rest is not at an angle to the keyboard by default. In fact, wrist rests have no default position. You are referring to a specific _design_: A variant of the DMOTE design where the fasteners that connect the wrist rest to the rest of the keyboard (the main body) are placed in such a way that you can adjust the distance between the two bodies after printing, by moving nuts. I chose the angle to accommodate various sizes of human hands touching both the thumb cluster and the rest of the keys.

Does this answer your question?

**Comment by Zentrik** [comment]
Yes, thank you.

**Comment by Zentrik** [comment]
How am i supposed to connect wrist rest and the main body? Am I supposed to 3d print a fastener like [here](https://user-images.githubusercontent.com/42909320/66863919-51516d80-ef94-11e9-9fc6-d448deaf4d82.jpg), if so how do I generate a stl for it. I tried using a m3 button screw, but I'm unclear how the head of the screw will not interfere with the wrist rest pad shape; the wrist rest is floating slightly above the ground and I don't see how you can adjust the distance between the wrist rest and main body easily.
