### ISSUE TITLE
What are the sources of supply for ﻿ALPS-style switches?

### ISSUE THREAD

**Issue by sieman** [veikman/dactyl-keyboard#30]
Dear Mr Veikman,
i like your keybard concertina design and i want to build one. 
Where do buy or get the ALPS-style switches? That is a big riddle for me.
Best regards,
Siegmar

**Comment by veikman** [comment]
I got my latest batch of ALPS-compatible Matias switches via the UK:
https://www.keyboardco.com/category.asp?path=Accessories/Switches

They ship to Sweden, so they will surely ship to Germany.

**Comment by veikman** [comment]
Closed for lack of activity.

**Comment by sieman** [comment]
I found also a other source for ALPS keys.
https://de.aliexpress.com/item/4000320410629.html

**Comment by veikman** [comment]
Cool!

The two types in that last link (“Clicky 30g Linear 60g”) do not include the Matias “Quiet Click” type I use the most of in my own builds.

**Comment by gluap** [comment]
I think they can also be bought directly from the manufacturer. https://matias.store/collections/switches currentlylists them at 50USD / 200 switches.
