### ISSUE TITLE
ordered dependency breaks with JDK11

### ISSUE THREAD

**Issue by dimitrisch** [veikman/dactyl-keyboard#5]
I was getting this error running `lein run` with the default setup:
> `Exception in thread "main" java.lang.IllegalArgumentException: Must hint overloaded method: toArray, compiling:(flatland/ordered/set.clj:12:1)`

The issue is pending [here](https://github.com/amalloy/ordered/pull/37) and until it is fixed I switched the dependency to [this fork](https://clojars.org/org.clojars.ctomo/ordered).

**Comment by veikman** [comment]
Thank you for posting a fix. Given the hubbub, I suppose it is likely @amalloy will take the PR and publish it pretty soon. Unless you object, I would rather wait than add the VCS noise of switching to a private fork.

**Comment by danielcompton** [comment]
This is now [available](https://github.com/clj-commons/ordered/releases/tag/1.5.7) in `[org.flatland/ordered "1.5.7"]`.

**Comment by veikman** [comment]
Nice. Local dependency updated in b7cc2d82f19d795b148d6b59c5977ee86c2d1a43.
