### ISSUE TITLE
How do I get started with this

### ISSUE THREAD

**Issue by rudenick1** [veikman/dactyl-keyboard#7]
nub Q: Will this article help me?: https://adereth.github.io/blog/2014/04/09/3d-printing-with-clojure/

 I haven't found any other way to contact

**Comment by veikman** [comment]
It depends on what you want to do. If you want to learn programmatic CAD, I would suggest you start by playing around with OpenSCAD itself before you graduate to `scad-clj` as @adereth suggests in the article you link to. To make advanced use of `scad-clj` you first need to familiarize yourself with Clojure. The best way to do that depends on your prior experience with other programming languages.

However, if you only what to build a DMOTE as the project stands today, you don’t need to know any of that stuff. The DMOTE project adds a layer of settings in YAML. There is an intro [here](https://github.com/veikman/dactyl-keyboard/blob/master/doc/intro.md). Basically, you git-clone this project, alter `default.yaml` or a personal file in your local copy, and render each tweak in OpenSCAD until the keyboard looks like it would fit your hands.

Does that help?

**Comment by rudenick1** [comment]
If you haven't considered it yet, please add it to FAQ. You really helped
me with this.

**Comment by veikman** [comment]
Glad to help. Please note the current state of this repository (`default.yaml` as included with the latest commit) is a snapshot, in between releases, so it is not currently suited even to my own hands. You should expect to print a number of prototypes before you get a shape that is right for you and ready to wire up.

Remember there is [more to comfortable typing](http://ergo.human.cornell.edu/AHTutorials/typingposture.html) than just the keyboard itself. I hope yours will turn out well.
