### ISSUE TITLE
Keycaps

### ISSUE THREAD

**Issue by TyberiusPrime** [veikman/dactyl-keyboard#9]
What keycap profile do you use?

The random set I have at hand seems a bit tight.

**Comment by veikman** [comment]
Thus far I have used [PMK](https://pimpmykeyboard.com/)’s DSA keycaps, which are indeed smaller than most other styles, though not especially narrow.

I am currently working on [a keycap library](https://github.com/veikman/dmote-keycap) to allow DMOTE previews with a wider variety of shapes, including angled OEM shapes, so you can check for a good fit before you print a DMOTE case, no matter what kind of caps you have. The `dmote-keycap` library can produce printable, useful models of “minimal” keycaps that wrap the body of a switch, so I can further compress the index-finger area on the DMOTE.

(Postcript: Printed caps aren’t pretty, but I use Matias switches and the market for injection-moulded ALPS-compatible caps is terrible. PMK does not currently sell the set I bought. I hope that the `dmote-keycap` library will eventually grow to meet basic needs. There are various free pure-OpenSCAD models already out there, including [OEM](https://www.thingiverse.com/thing:468651) and DSA.)

**Comment by TyberiusPrime** [comment]
Thank you for your quick response, I'll be ordering some dsa caps:)
